### ISSUE TITLE
Recent commit broke installation of module

### ISSUE THREAD

**Issue by dizzystuff** [silverstripe-australia/silverstripe-multisites#43]
Hi guys. Love this mod and use it often. Just trying to install it on a fresh 3.1.x and finding that on db build I'm getting a MySQL error along the lines of "Table dbname.SiteTree doesn't exist".

Some digging around and I'm quite certain the issue was moving onAfterInit() code from MultisitesContentControllerExtension to MultisitesControllerExtension in 6ebf49b

The code is now being called on controllers DevelopmentAdmin, DevBuildController and DatabaseAdmin - at which point in time for a fresh install there are no tables yet, but we're going searching for getCurrentSite()... hence the error.

I'm not certain of the best prac way around this. Perhaps removing the extension on Controller, and instead extending the onAfterInit() func onto a specific set of Controllers, excluding the base class and the controllers listed above? Seems pretty verbose though. 

In the meantime I've wrapped the code inside an ugly but functional !in_array():

```php
public function onAfterInit() {

		if (!in_array(get_class($this->owner), array('DevelopmentAdmin', 'DevBuildController', 'DatabaseAdmin'))) {

			$site = Multisites::inst()->getCurrentSite();

			if($site && $theme = $site->getSiteTheme()) {
				SSViewer::set_theme($theme);
			}
		}
	}
```

I'm happy to submit a PR with a fix if y'all can a) confirm I'm not going crazy and b) suggest the best method of fix?

**Comment by dizzystuff** [comment]
Awesome. Thanks @nyeholt :)

**Comment by nyeholt** [comment]
It's not the best fix, but will do for now until I next do something with the module :)
