### ISSUE TITLE
3.2 compatibility / composer file?

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe-australia/silverstripe-multisites#48]
Composer.json wants a 3.1.x version, so installing with 3.2 might be problematic.

**Comment by Zauberfisch** [comment]
I have forked and updated the module to support 3.2: https://github.com/Zauberfisch/silverstripe-multisites

however, there where some [breaking api changes](https://github.com/silverstripe/silverstripe-framework/issues/4703), so I will wait with a pull request until that issue is resolved.

**Comment by tractorcow** [comment]
Does this fix your issue? https://github.com/silverstripe/silverstripe-cms/pull/1320

**Comment by Zauberfisch** [comment]
@tractorcow, yes, thank you.
However, there still is:

    [Strict Notice] Declaration of Multisites_SideReport_BrokenLinks::sourceRecords() should be compatible with BrokenLinksReport::sourceRecords($params, $sort, $limit)

Question is though, if we should fix that in core or the module.

**Comment by Zauberfisch** [comment]
this issue has been fixed, @wernerkrauss mind closing it?
