### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by Codesesh** [silverstripe-australia/silverstripe-multisites#70]
Hi guys,

We are using Silverstripe 3.5.1 currently and using the multisite module. We have noticed that you can't drag and drop pages around?

If you click into a page, it brings up a "Edit tree" button at the top:

![hiking-before](https://cloud.githubusercontent.com/assets/12224994/23628286/b4839db2-0318-11e7-80c0-7c56ce7b9904.png)

If you click the "Edit tree" button it just reloads the page, and shows the other 2 buttons at the top like so:

![hiking-after](https://cloud.githubusercontent.com/assets/12224994/23628295/b833d15c-0318-11e7-9de0-48a3d0eb4890.png)

Meanwhile you cannot drag and drop the pages around at all...

Is there a config setting I am missing? Or is this a bug?

**Comment by nyeholt** [comment]
Drag and drop is a bug - need to look into the edit tree stuff a bit more.

**Comment by xini** [comment]
this is fixed and tagged as release 3.0.0

**Comment by nyeholt** [comment]
Sorry about that @Codesesh I forgot to update this issue :) As Florian mentioned, this has been released as 3.0.0 - the fixes aren't backwards compatible with 3.2, hence the new major version number.
